[versions]
appVersion = "3.3.0"
kotlinVersion = "1.9.10"
kotlinCoroutines = "1.7.3"
minSdk = "22"
targetSdk = "34"
compileSdk = "34"
jdk = "17"
gradleVersion = "8.1.1"
androidxCore = "1.12.0"
material = "1.9.0"
navigation = "2.7.3"
lifecycle = "2.6.2"
constraintLayout = "2.1.4"
annotation = "1.7.0"
appcompat = "1.6.1"
fragment = "1.6.1"
work = "2.8.1"
preference = "1.2.1"
okhttp = "4.11.0"
retrofit = "2.9.0"
picasso = "2.71828"
moshi = "1.15.0"
junit = "4.13.2"
testRunner = "1.5.2"
espressoCore = "3.5.1"

[libraries]
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradleVersion" }
kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinVersion" }
navigation-safe-args-plugin = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "navigation" }

kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlinVersion" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlinVersion" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }

annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picasso" }

retrofit-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

moshi-moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }

okhttp-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }

work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
work-gcm = { module = "androidx.work:work-gcm", version.ref = "work" }

preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }

test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
test-junit = { group = "junit", name = "junit", version.ref = "junit" }
